### ISSUE TITLE
InvalidCertificateChainException

### ISSUE THREAD

**Issue by mwkirk** [mwkirk/javapns#139]
_Original author: msitestf...@gmail.com (July 25, 2012 08:20:20)_

<b>What steps will reproduce the problem?</b>
1. JAVA pns connection initialized successfully
2. Then call below line to check ths push notification status

List&lt;PushedNotification&gt; notifications = Push.alert(&quot;Test HOV notification&quot;,certificate, passwd, false, devices); 

check th status return error like solution for 

javapns.communication.exceptions.InvalidCertificateChainException: Invalid certificate chain (Received fatal alert: certificate_unknown)! Verify that the keystore you provided was produced according to specs...

this error return from some machine (Windows 2008 - AWS enabled)
1. But the same apple certificate working in other machine(Windows 2003,Windows xp)

<b>What is the expected output? What do you see instead?</b>

Receiver iphone need to be get pushed notification. At sender iphone got the above error and receiver nothing get.

<b>What version of the product are you using? On what operating system?</b>

Operationg system : windows 2008

version product : JAVAPNS 2.2 and Jdk1.7.0,jre7

<b>Please provide any additional information below.</b>

 Connection initialized from this server by using same certificate. But sending failed.

 Same certificate send notification also in other machine. How it possible to failure in particular machine?

_Original issue: http://code.google.com/p/javapns/issues/detail?id=139_

**Comment by mwkirk** [comment]
_From sype...@gmail.com on July 25, 2012 13:55:41_
Could you try with Java 6?  I've seen a few reports that SSL is behaving strangely under Java 7, but without any hard evidence...

**Comment by mwkirk** [comment]
_From msitestf...@gmail.com on July 28, 2012 08:31:36_
Thank you. This comment help to me

**Comment by mwkirk** [comment]
_From sype...@gmail.com on August 11, 2012 18:05:22_
Closing this issue report since the workaround was successful, but I also added relevant documentation about Java 7 in the Requirements documentation page.

**Comment by 37-int** [comment]
I solved the issue in jdk 1.7 and using p12, just after changing the passwd length of p12 file greater than or equal 6. Otherwise, the following error happens:
[[1] not transmitted to token 595d8..725bf  javapns.communication.exceptions.InvalidCertificateChainException: Invalid certificate chain (Received fatal alert: certificate_unknown)!  Verify that the keystore you provided was produced according to specs...]

**Comment by mahenderk** [comment]
Please add  jssecacerts file to our $JAVA_HOME/lib/security/jssecacerts. It will solve the issue. Download from this link: https://github.com/notnoop/java-apns/wiki
